# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chestinfectionapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://chestinfectionapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8017176c265540efaa874a03a1347a5b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_981b8a7228a24abd97dc344430e4edf6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chestinfectionapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8017176c265540efaa874a03a1347a5b }}/chest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chestinfectionapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2f2eea00af9b4b188843db632cc3ab2f }}
        images: 'chestinfectionapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8017176c265540efaa874a03a1347a5b }}/chest:${{ github.sha }}'